[build]
cmd = "go build -o ./tmp/main cmd/*.go"
bin = "tmp/main"
full_bin = "APP_ENV=dev ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
level = "debug"

[misc]
clean_on_exit = true
