server:
  port: 8080 
  host: "localhost"

logging:
  log_level: "INFO" # Options: INFO, WARN, DEBUG, ERROR
  log_file: ./server.log # The location where the log file will be stored

database:
  path: ./shortener.db # Location where the database file will be stored  

shortcodes:
  shortcode_universe: "abcdefghijklmnopqrstuvwxyz" # Characters allowed for use in shortcodes
  shortcode_length: 6 # Length of shortcodes in characters

auth:
  tls_cert: "cert.pem" # Path to TLS certificate
  tls_key: "key.pem" # Path to TLS key
  cookie_max_age_days: 7 # Cookie max age in days 
  cookie_secret: "secret"

hcaptcha:
  secret_key: "abcd"
  site_key: "abcde"
