server:
  port: 8080 
  host: "localhost"

shortcodes:
  shortcode_universe: "abcdefghijklmnopqrstuvwxyz"
  shortcode_length: 6

auth:
  root_username: "root"
  root_password: "root"
  tls_cert: "cert.pem"
  tls_key: "key.pem"
  cookie_secret: "secret"
  api_key_length: 32
